language: go
go: '1.14'
env:
- GO111MODULE=on
script: make all
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist --skip-validate
    on:
      tags: true
notifications:
  email: false
