log_format = "text"
log_level = "debug"
token = "hello"

# handlers will be registered in the order they are specified here.
# -----------------------------------------------------------------

[[handlers]]
name = "echo_greeting"
type = "simple"
match = [
    "^(hi|hello|howdy)$"
]
message = [
  "{{.event.Text}}"
]

[[handlers]]
name = "match_all"
type = "command"
match = [
    ".*"
]
cmd = "./hello.sh"
timeout = "5s"