log_format = "text"
log_level = "debug"
token = "hello"

# handlers will be registered in the order they are specified here.
# -----------------------------------------------------------------

# this handler simply echoes back the message
[[handlers]]
name = "echo_hi"
type = "echo"
match = [
    "^(hi|hello|howdy)$"
]

[[handlers]]
name = "match_all"
type = "command"
match = [
    ".*"
]
cmd = "./hello.sh"
timeout = "5s"